# Generated by Django 3.2.8 on 2021-12-06 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_uielements', models.TextField(null=True)),
                ('detected_boundboxs', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('transaction_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('failed', 'Failed'), ('successfull', 'Successfull')], default='successfull', max_length=11)),
                ('ml_models', models.CharField(choices=[('yolov5', 'YOLOV5'), ('yolox', 'YOLOX'), ('faster_rcnn', 'Faster - RCNN')], default='yolov5', max_length=11)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-transaction_datetime',),
            },
        ),
    ]
