# Generated by Django 3.2.8 on 2021-12-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='image_to_detect',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
    ]
