# Generated by Django 3.2.8 on 2021-12-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_transaction', '0002_transaction_image_to_detect'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='confidence',
            field=models.IntegerField(default=0.25),
        ),
    ]
