# Generated by Django 3.2.8 on 2021-12-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_transaction', '0003_transaction_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='confidence',
            field=models.FloatField(default=0.25),
        ),
    ]
