# Generated by Django 3.2.8 on 2021-12-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_transaction', '0004_alter_transaction_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('html', 'HTML'), ('pyqt', 'PyQt')], default='html', max_length=11),
        ),
    ]
